name: news_uss
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  dio: ^5.4.3+1
  equatable: ^2.0.5
  floor: ^1.4.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  get_it: ^7.7.0
  retrofit: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  retrofit_generator: ^8.1.0
  build_runner: ^2.4.9
  floor_generator: ^1.4.2

flutter:
  uses-material-design: true

  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/mulish/Mulish-Regular.ttf
          weight: 400
        - asset: assets/fonts/mulish/Mulish-Bold.ttf
          weight: 700
        - asset: assets/fonts/mulish/Mulish-Light.ttf
          weight: 300
